management:
  context-path: /admin
  add-application-context-header: false

server:
  port: 80
  
spring:
  datasource:
    url: jdbc:mysql://localhost/adtech
    username: adtechapp

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 150
  